[package]
name = "basilisk-escrow"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "basilisk_escrow"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
solana-program = "1.18.0"

[dev-dependencies]
solana-program-test = "1.18.0"
solana-sdk = "1.18.0"
